### ISSUE TITLE
Add the branch in the Change object

### ISSUE THREAD

**Issue by morucci** [morucci/monocle#4]

**Comment by flepied** [comment]
that could help in some analysis I would like to do like being sure a ticker is linked to the PR. Some ticketing systems allow to have the ticket number in the branch name, in the title or in the description.

**Comment by morucci** [comment]
Ok in that case you mean the "from" branch. Have a ticket number in the "from" branch. Here it about the PR target branch but both are nice piece of information. As the "from" branch make sense in the PR model, it does not in a Gerrit/Review model. But it can be set to "master" by default for gerrit maybe ?

**Comment by flepied** [comment]
yes I agree we need both branches
